@startuml
'https://plantuml.com/class-diagram

class Password implements Credencial
class QR implements Credencial
class SecurityCode implements Credencial
interface Credencial

class User{
    credencialesCorrectas(user:Usuario, acces: Credencial)
}

class AlgoMail{
}


AlgoMail .left.> SimpleAuthentication
AlgoMail ..> MultipleAuthentication
AlgoMail ->"0..*" User
User "1"<--"1..2" Credencial
@enduml