@startuml
'https://plantuml.com/class-diagram

class Paquete
class Envio

interface Envoltorio
interface Marcado
interface TipoEnvio
class Veloz implements TipoEnvio
class Normal implements TipoEnvio


Envio *-- TipoEnvio
Envio --> Paquete
Paquete o-- Envoltorio
Paquete o-- Marcado


@enduml