@startuml
'https://plantuml.com/class-diagram

interface TipoEntrada{
    -cantidadTickets
}
class EntradaMayor implements TipoEntrada
class EntradaMenor implements TipoEntrada
class EntradaComun implements TipoEntrada


class Evento{
    -cantidadTickets
}

class Entrada

Entrada --o TipoEntrada
Evento --> Entrada

@enduml