@startuml
'https://plantuml.com/class-diagram

Actor actor

participant Evento as event
participant Entrada as entrada
participant "TipoEntrada: EntradaMayor" as tipo

actor --> event: cantidadEntradas([73, 78])
loop Cada Edad
    event --> entrada: obtenerEntrada(edad)
    entrada --> tipo: obtenerTickets()
    return 3
    entrada --> event: 3
end



event --> event: hayEntradasDisponibles(6)
event --> actor: 6
@enduml